# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XinFinDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XinFinDemo

  pod 'Alamofire', '~> 4.9.0'
  pod 'SwiftyJSON'

  target 'XinFinDemoTests' do
    # Pods for testing
  end

end
